BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: "+"
            on_press: app.handle_increment(1)
        TextInput:
            id: input_miles
            hint_text: "Miles"
        Button:
            text: "-"
            on_press: app.handle_increment(-1)
    Button:
        text: "Convert"
        on_press: app.handle_convert()
    Label:
        text: app.result_text
